language: node_js
node_js:
  - "7"
env:
  JWT_KEY: secret
cache:
  directories:
    - "node_modules"
sudo: false
dist: trusty
services:
  - postgresql
before_script:
  - "psql -c 'create database weconnect_test;' -U postgres"
  - npm run test-migrate
after_success: 
  - npm run coverage
  - npm run check-coverage