language: node_js
node_js:
  - "7"
env:
  - MY_SECRET=This
cache:
  directories:
    - "node_modules"
sudo: false
dist: trusty
services:
  - postgresql
before_script:
  - psql -c 'create database database_test;' -U postgres
  - psql -c "CREATE USER seun WITH PASSWORD 'password';" -U postgres
script:
  - npm run test
after_success: 
  - npm run coverage