language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- NODE_ENV=test DB_USERNAME=seun DB_PASSWORD=pass DB_DATABASE=wecon MY_SECRET=This is my secret
before_script:
- psql -c 'create database wecon;' -U postgres
- psql -c "CREATE USER seun WITH PASSWORD 'pass';" -U postgres
script: npm test
